"""
Django settings for junk project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

from thisaintjack import site_config

THISAINTJACK_HOME = site_config.THISAINTJACK_HOME
THISAINTJACK_URL  = site_config.THISAINTJACK_URL
SECRET_KEY        = site_config.SECRET_KEY
ADMINS            = site_config.ADMINS

MANAGERS = ADMINS

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY        = site_config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG


ALLOWED_HOSTS = ['.fandangobrc.com', ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'campmanager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thisaintjack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(THISAINTJACK_HOME, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]


WSGI_APPLICATION = 'thisaintjack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = site_config.THISAINTJACK_DATABASES


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = '/home/neowolf/FandangoRegistration/public/static/'

STATIC_URL = '/static/'


AUTHENTICATION_BACKENDS = (
    #'social_auth.backends.twitter.TwitterBackend',
    #'social_auth.backends.facebook.FacebookBackend',
    #'social_auth.backends.google.GoogleOAuth2Backend',
#    'social_auth.backends.yahoo.YahooBackend',

    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.yahoo.YahooOpenId',
    'social_core.backends.facebook.FacebookOAuth2',
    #'django_openid_auth.auth.OpenIDBackend',
    'django.contrib.auth.backends.ModelBackend',
)


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = site_config.GOOGLE_OAUTH2_CLIENT_ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = site_config.GOOGLE_OAUTH2_CLIENT_SECRET
SOCIAL_AUTH_FACEBOOK_KEY = site_config.FACEBOOK_APP_ID
SOCIAL_AUTH_FACEBOOK_SECRET = site_config.FACEBOOK_API_SECRET

#TWITTER_CONSUMER_KEY         = site_config.TWITTER_CONSUMER_KEY
#TWITTER_CONSUMER_SECRET      = site_config.TWITTER_CONSUMER_SECRET
#FACEBOOK_APP_ID              = site_config.FACEBOOK_APP_ID
#FACEBOOK_API_SECRET          = site_config.FACEBOOK_API_SECRET

LOGIN_URL          = '/user/login/'
LOGIN_REDIRECT_URL = '/user/profile'
LOGIN_ERROR_URL    = '/user/login_error/'

SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/user/login_created/'
SOCIAL_AUTH_DEFAULT_USERNAME = 'oauth_user'
SOCIAL_AUTH_EXPIRATION = 'expires'
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ['email',]
SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = '/user/disconnected/'
SOCIAL_AUTH_BACKEND_ERROR_URL = '/user/login_error'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.9'

#SOCIAL_AUTH_USER_MODEL = 'foo.bar.User'


#SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/logged-in/'
#SOCIAL_AUTH_LOGIN_ERROR_URL = '/login-error/'
#SOCIAL_AUTH_LOGIN_URL = '/login-url/'
#SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/new-users-redirect-url/'
#SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/new-association-redirect-url/'
#SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = '/account-disconnected-redirect-url/'
#SOCIAL_AUTH_INACTIVE_USER_URL = '/inactive-user/'

SOCIAL_AUTH_PIPELINE = (
    #'social_core.pipeline.social_auth.social_details',
    #'social_core.pipeline.social_auth.social_uid',
    #'social_core.pipeline.social_auth.social_user',
    #'social_core.pipeline.user.get_username',
    #'social_core.pipeline.user.create_user',
    #'social_core.pipeline.social_auth.associate_user',
    #'social_core.pipeline.social_auth.load_extra_data',
    #'social_core.pipeline.user.user_details',
    #'social_core.pipeline.social_auth.associate_by_email',

    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.social_auth.associate_user',
    #'social_core.pipeline.social_auth.load_extra_data',
    #'social_core.pipeline.user.user_details',
)
